on: push
name: Main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - id: validate
      uses: igabaydulin/helm-check-action@0.1.4
      env:
        CHART_LOCATION: ./helm-check-action-sample
